export const rawData = {
  guid: "feed30bd43114fd28ab116db2c9a79aa",
  // type: "ColumnChart",
  position: {
    x: 237,
    y: 101
  },
  // positionLocked: false,
  // size: {},
  // title: {},
  // frame: {},
  // background: {},
  // boxShadow: {},
  zIndex: 1,
  // selectedFilterValues: {},
  // multiselectEnabled: false,
  // userChangedSelectedValuesInCurrentSession: false,
  // useCustomColors: false,
  // drilldownEnabled: false,
  allowedDatasourceType: [],
  // codeEditableEnabled: true,
  // overriddenCode: "console.log(w);\nHighcharts.chart(...);",
  // dataSettings: {},
  themeGuid: null,
  // numberFormat: {},
  // legend: {},
  // yAxis: {},
  // yAxisOpposite: {},
  // xAxis: {},
  // series: [],
  // dataLabels: {},
  // tooltip: {},
  // controlPanel: {},
  // column: {},
  // stackedLabel: {},
  isManualColumnSettings: false,
  isStacking: false,
  nullDataHandling: 0,
  colorPalette: [{"id": "cb374a832342428cb43a0453a9b72566","value": "rgba(40, 238, 150, 1)"}]
};
